# Application bindings
bindd = ALT, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"
bindd = ALT, B, Browser, exec, omarchy-launch-browser
bindd = ALT, E, Email, exec, omarchy-launch-browser "https://mail.google.com/"
bindd = ALT, C, Calendar, exec, omarchy-launch-browser "https://calendar.google.com/"
bindd = ALT, M, Money, exec, omarchy-launch-browser "https://notion.so/"
bindd = ALT, D, Design, exec, omarchy-launch-browser "https://canva.com/"
bindd = ALT, [, Editor, exec, omarchy-launch-editor
bindd = ALT, W, Typora, exec, uwsm-app -- typora --enable-wayland-ime

# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment
bindd = ALT, X, X Post, exec, omarchy-launch-webapp "https://x.com/compose/post"

# Add extra bindings
# bind = SUPER SHIFT, R, exec, alacritty -e ssh your-server

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER, SPACE
# bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu

# Logitech MX Keys
bindd = SUPER ALT, C, Screenshot, exec, omarchy-capture-screenshot      # Print Screen Button
bindd = ALT, 9, Dictate, exec, voxtype record toggle                 # Dictation Button
bindd = ALT, PERIOD, Emoji, exec, omarchy-launch-walker -m symbols # Emoji Button
